name: Deploy to staging
on:
  push:
    branches: 
     - "main"

jobs:
  redoply_everything:
    name: Deploying everything to staging
    steps:
     - name: SSH into Server
       run: |
        echo ${{secrets.SSH_PRIVATE_KEY}} > ~/ssh_key
        chmod 700 ~/ssh_key
        ssh -i ~/ssh_key ubuntu@13.233.115.45 "cd deployement_sample && git pull && pnpm install && pnpm run build && pm2 restart all"
